--- Add locations
INSERT INTO public.location (city, country) VALUES ('New York', 'USA'),
('Boston', 'USA'),
('Washington D.C', 'USA'),
('Chicago', 'USA'),
('Dallas', 'USA'),
('Austin', 'USA'),
('San Diego', 'USA'),
('Seattle', 'USA'),
('San Francisco', 'USA'),
('Denver', 'USA'),
('Los Angeles', 'USA'),
('Toronto', 'Canada'),
('Montreal', 'Canada'),
('Vancouver', 'Canada'),
('Ottawa', 'Canada'),
('Mexico City', 'Mexico'),
('Barcelona', 'Spain'),
('Madrid', 'Spain'),
('Paris', 'France'),
('London', 'UK'),
('Tokyo', 'Japan'),
('Kyiv', 'Ukraine'),
('Moscow', 'Russia'),
('Berlin', 'Germany'),
('Stockholm', 'Sweden'),
('Copenhagen', 'Denmark'),
('Hong Kong', 'China'),
('Shenzhen', 'China'),
('Shanghai', 'China'),
('Beijing', 'China');