--- Add skills
INSERT INTO public.skill (name, created_date) VALUES
    ('Javascript', now()),
    ('Java', now()),
    ('Python', now()),
    ('Kotlin', now()),
    ('Scala', now()),
    ('AngularJS', now()),
    ('React', now()),
    ('Vue.js', now()),
    ('Redux', now()),
    ('MobX', now()),
    ('C#', now()),
    ('C', now()),
    ('C++', now()),
    ('Objective-C', now()),
    ('Swift', now()),
    ('ActionScript', now()),
    ('ASP.NET', now()),
    ('CSS', now()),
    ('Delphi', now()),
    ('Erlang', now()),
    ('Elixir', now()),
    ('F#', now()),
    ('Go', now()),
    ('Haskell', now()),
    ('HTML', now()),
    ('HTML5', now()),
    ('IDL', now()),
    ('Node.js', now()),
    ('NPM', now()),
    ('Bootstrap', now()),
    ('jQuery', now()),
    ('MySQL', now()),
    ('OOP', now()),
    ('OCaml', now()),
    ('Perl', now()),
    ('PHP', now()),
    ('PL/SQL', now()),
    ('PostgreSQL', now()),
    ('PostScript', now()),
    ('R', now()),
    ('RavenDB', now()),
    ('Ruby', now()),
    ('Ruby on Rails', now()),
    ('SQLite', now()),
    ('UML', now()),
    ('Unix', now()),
    ('Visual Basic', now()),
    ('XML', now()),
    ('XSL', now()),
    ('AI', now()),
    ('Backbone.js', now()),
    ('Cocoa', now()),
    ('CodeIgniter', now()),
    ('CORBA', now()),
    ('CVS', now()),
    ('DOM', now()),
    ('FFmpeg', now()),
    ('Git', now()),
    ('JSON', now()),
    ('Laravel', now()),
    ('Machine Learning', now()),
    ('MantisBT', now()),
    ('Mercurial', now()),
    ('.NET', now()),
    ('Network Programming', now()),
    ('OAuth', now()),
    ('OAuth2', now()),
    ('OpenCL', now()),
    ('OpenID', now()),
    ('OpenSSL', now()),
    ('OS Development', now()),
    ('Project Management', now()),
    ('RegEx', now()),
    ('SSH', now()),
    ('SOAP', now()),
    ('Vi', now()),
    ('WCF', now()),
    ('WSDL', now()),
    ('YUI', now()),
    ('Zikula', now()),
    ('Linux Programming', now()),
    ('Raspberry Pi', now()),
    ('Ubuntu', now()),
    ( 'Jira', now()),
    ( 'Confluence', now()),
    ( 'Trello', now()),
    ( 'Lua', now()),
    ( 'Reactive Programming', now()),
    ( 'RxJava', now()),
    ( 'Spring Framework', now()),
    ( 'Hibernate', now()),
    ( 'Oracle Database', now()),
    ( 'Microsoft SQL Server', now()),
    ( 'Ember.js', now()),
    ( 'Photoshop', now()),
    ( 'iOS', now()),
    ( 'Rust', now()),
    ( 'Unity', now()),
    ( 'Android', now());