# Java Maven CircleCI 2.0 configuration file
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    working_directory: ~/mango-build
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: D30f$83fe%1917_3ab42
          POSTGRES_DB: mango-test

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx1G

    steps:
      - checkout
      - restore_cache:
          keys:
            - circleci-mango-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Get maven dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-mango-{{ checksum "pom.xml" }}
      - run:
          name: Running tests
          command: mvn package
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit  
      # Upload code coverage to Codecov: https://codecov.io/
      - codecov/upload:
          file: ~/mango-build/target/jacoco-reports/jacoco.xml
      - store_artifacts: # store the uber jar as an artifact
          path: target/mango-1.0.0-SNAPSHOT.jar
          destination: ~/mango-build/artifact-storage/mango-1.0.0-SNAPSHOT.jar
