export const testPositions = '\
[{"id":1,"position":"Senior Backend Engineer","skills":[{"languages":["Python","JS"]},{"frameworks":["Django"]},{"libraries":["AWS"]},{"tools":["PyChart"]},{"databases":["Num Py"]},{"platforms":["io"]},{"environments":["etc"]}],"type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":true},\
{"id":2,"position":"UX designer","skills":[{"languages":["Python"]},{"frameworks":["Django","JS"]},{"libraries":["AWS"]},{"tools":["PyChart"]},{"databases":["Num Py"]},{"platforms":["io"]},{"environments":["etc"]}],"type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":true},\
{"id":3,"position":"Front End Developer","skills":[{"languages":["Python"]},{"frameworks":["Django"]},{"libraries":["AWS"]},{"tools":["PyChart"]},{"databases":["Num Py"]},{"platforms":["io"]},{"environments":["etc"]}],"type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":true},\
{"id":4,"position":"Product Designer Lead","skills":[{"languages":["Python"]},{"frameworks":["Django"]},{"libraries":["AWS"]},{"tools":["PyChart"]},{"databases":["Num Py"]},{"platforms":["io"]},{"environments":["etc"]}],"type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":false},\
{"id":5,"position":"Project Manager","skills":[{"languages":["Python"]},{"frameworks":["Django"]},{"libraries":["AWS"]},{"tools":["PyChart"]},{"databases":["Num Py"]},{"platforms":["io"]},{"environments":["etc"]}],"type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":false},\
{"id":6,"position":"Senior Backend Engineer","skills":[{"languages":["Python"]},{"frameworks":["Django"]},{"libraries":["AWS"]},{"tools":["PyChart"]},{"databases":["Num Py"]},{"platforms":["io"]},{"environments":["etc"]}],"type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":false},\
{"id":7,"position":"Manual Engineer","skills":[{"languages":["Python"]},{"frameworks":["Django"]},{"libraries":["AWS"]},{"tools":["PyChart"]},{"databases":["Num Py"]},{"platforms":["io"]},{"environments":["etc"]}],"type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":false},\
{"id":8,"position":"Manual Engineer","skills":[{"languages":["Python"]},{"frameworks":["Django"]},{"libraries":["AWS"]},{"tools":["PyChart"]},{"databases":["Num Py"]},{"platforms":["io"]},{"environments":["etc"]}],"type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":false}]\
';