export const testPositions = '\
[{"id":1,"position":"Senior Backend Engineer","skills":"Angular JS, JavaScript, NodeJS/Express, MySQL, PHP, Python, Django, AWS, PyChart, Num Py","type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":true},\
{"id":2,"position":"UX designer","skills":"Angular JS, JavaScript, NodeJS/Express, MySQL, PHP, Python, Django, AWS, PyChart, Num Py","type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":true},\
{"id":3,"position":"Front End Developer","skills":"Angular JS, JavaScript, NodeJS/Express, MySQL, PHP, Python, Django, AWS, PyChart, Num Py","type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":true},\
{"id":4,"position":"Product Designer Lead","skills":"Angular JS, JavaScript, NodeJS/Express, MySQL, PHP, Python, Django, AWS, PyChart, Num Py","type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":false},\
{"id":5,"position":"Project Manager","skills":"Angular JS, JavaScript, NodeJS/Express, MySQL, PHP, Python, Django, AWS, PyChart, Num Py","type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":false},\
{"id":6,"position":"Senior Backend Engineer","skills":"Angular JS, JavaScript, NodeJS/Express, MySQL, PHP, Python, Django, AWS, PyChart, Num Py","type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":false},\
{"id":7,"position":"Manual Engineer","skills":"Angular JS, JavaScript, NodeJS/Express, MySQL, PHP, Python, Django, AWS, PyChart, Num Py","type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":false},\
{"id":8,"position":"Manual Engineer","skills":"Angular JS, JavaScript, NodeJS/Express, MySQL, PHP, Python, Django, AWS, PyChart, Num Py","type":"Full Time","remote":"No","experience":"4-6+ years","industry":"Energy","location":{"city":"Seattle","country":"USA"},"relocation":"Yes","visaSponsor":"Yes","date":"08.09.2018","isChecked":false}]\
';