  export const TOGGLE_JOB_STATUS = 'TOGGLE_JOB_STATUS';
  export const TOGGLE_MARK_TALENT = 'TOGGLE_MARK_TALENT';
  export const DELETE_TALENT = 'DELETE_TALENT';
  export const DELETE_JOB = 'DELETE_JOB';
  export const CLOSE_MOBILE_MENU = 'CLOSE_MOBILE_MENU';
  export const OPEN_MOBILE_MENU = 'OPEN_MOBILE_MENU';